### PR TITLE
Added support for Shattering Steel shotgun mechanic

### PR DESCRIPTION
**Pull request by meatballing**
https://feathub.com/LocalIdentity/PathOfBuilding/+10

Same implementation as barrage support

### CODE REVIEW

**Comment by LocalIdentity** [comment]
You need to update the act_dex.txt export script too when making changes to the gemlua files

**Comment by meatballing** [comment]
Curious to understand what the export scripts are for.

**Comment by LocalIdentity** [comment]
> Curious to understand what the export scripts are for.

The export scripts export a whole bunch of data directly from the GGPK file and are how the gem files are created

**Comment by LocalIdentity** [comment]
Also since I'm guessing you're not in the PoB fork discord, add me LocalIdentity#9871

**Comment by meatballing** [comment]
Updated to correctly handle aoe modifiers on the initial hit and the cone

**Pull request merged**
