### PR TITLE
Fungal ground

### PR DESCRIPTION
**Pull request by rskupnik**
Not a very useful thing, just a basic task to familiarize myself with the structure of the codebase. Please let me know if there is anything more needed to be done here that I am not aware of.

### CODE REVIEW

**Comment by Quotae** [comment]
Your code looks fine for where it is, but ModCache.lua is the wrong file to add the mod to! The proper file is in /Modules/ModParser-3_0.lua. ModCache is a file that PoB generates based on the contents of ModParser, so if your new mods aren't in ModParser, this ModCache will be overwritten next time it gets refreshed and the mod won't work anymore.

ModParser and ModCache have slightly different formatting but it shouldn't be too hard to figure out if you figured out ModCache!

**Comment by rskupnik** [comment]
Thanks for the info, I'll fix that soon :)  Just for clarity, does POB store it's ModCache somewhere in its files and the ModCache in repo is just a static file?

**Comment by ppoelzl** [comment]
The ModCache has to be rebuilt manually according to https://github.com/Openarl/PathOfBuilding/blob/master/CONTRIBUTING.md for new mods to be supported. Usually, changes to it are only commited to Github on a new release.

**Comment by ppoelzl** [comment]
At least for all Lua files, the directory structure in the installed version matches the one of the repository.

**Comment by rskupnik** [comment]
Thanks, I figured out how to reload the cache. I'm just struggling to make the parser parse a string with parentheses and dots in it, despite escaping them

**Comment by rskupnik** [comment]
Alright, I've updated the ModParser-3.0 and got the escaping working properly (forgot that the dash needs to be escaped too >.> )

**Comment by Quotae** [comment]
Yeah I have a feeling Openarl only modifies ModCache when he adds stuff to ModParser. I know LocalIdentity had this exact same confusion between ModCache and ModParser when he first started, so I hope he's been updating it as he goes lol.

It's pretty easily refreshed for yourself in dev mode by pressing ctrl+F5, it only takes a few seconds to build the file. It's just a matter of actually updating the file in the repo.

**Pull request merged**
