### PR TITLE
Implemented more/less min/max damage for Ryslatha's Coil

### PR DESCRIPTION
**Pull request by dragbone**
Implemented more/less min/max damage for Ryslatha's Coil.
@LocalIdentity I have included the rebuilt ModCaches in this PR, do you prefer just the file changes and then rebuilding the caches yourself?
I'm not really happy with how the mods are retrieved but I have no better idea.

### CODE REVIEW

**Comment by LocalIdentity** [comment]
Usually, I edit the ModCache myself and keep it on individual lines so it's much easier to compare changes. Is there an auto way to build the cache?

**Comment by dragbone** [comment]
Yes, holding `Ctrl` while starting PoB rebuilds the cache (see https://github.com/LocalIdentity/PathOfBuilding/blob/master/CONTRIBUTING.md#setting-up-a-development-install for other useful keys)

**Comment by LocalIdentity** [comment]
I knew of the other shortcuts but somehow missed that one.

**Comment by LocalIdentity** [comment]
Added in 1.4.153.1

**Pull request closed without merging**
