### PR TITLE
Support Barrage Support

### PR DESCRIPTION
**Pull request by Quotae**
- Supports DPS multiplier per projectile
- Supports more attack time per projectile
- Supports more trap/mine throwing time per projectile
- Adds better breakdowns in the Calcs tab for attack time, trap/mine throwing rate, and trap/mine throwing time

image
image

Old pull request was #85 .

This time it's all automatic! Using a skill flag, as suggested in the first PR, was something I hadn't tried because I was focusing too hard on making it work with just Barrage Support. But adding a flag makes it work with more things in the future, so it definitely makes sense to do it this way instead. The flag name I went with was "SequentialProjectiles" because that's the word used right on the Barrage/Barrage Support gems. "SuccessiveProjectiles" was another choice, which is the word used on the Ice Spear gem, but I liked sequential more. I didn't use FiresInAVolley because Volley isn't a word exclusive to this projectile behavior, so it didn't make sense to use it for this functionality.

I didn't apply this new flag to the Barrage skill or to Ice Spear because those skills have stages with which to switch between projectile counts. It would be relatively easy to apply to them, though, if that makes more sense for some reason.

ALSO, all the modifiers to attack time and throwing times are more generic now and don't reference Barrage Support at all. With the new way I did it, any modifier to "AttackTimeMod" or "MineThrowingTimeMod" or "TrapThrowingTimeMod" should change the respective time, instead of it ONLY working for Barrage Support and being a more multiplier. I know that those variable names suck but I couldn't really think of anything else, and just directly modifying the base MineThrowingTime or whatever didn't seem to work correctly. Could easily be changed by me or someone else before it gets committed because the only places it's used are in SkillStatMap.lua and then CalcOffence-3_0.lua where they're actually used. For now though, the names are clear and everything's functional based on my testing.

Hopefully this PR is better! Let me know any concerns or problems.

### CODE REVIEW

**Comment by Quotae** [comment]
The problem with just removing "Mod" from the variable name is that AttackTime etc. are the names of the base values. I originally started by just directly modifying the base times(which are defined in CalcSetup.lua) but I couldn't get the Calcs tab stuff to work how I wanted it to. Which I guess I'll explain real quick, because it's what made the most sense to me.

The base time here is what you final throwing time would be after all your modifiers to throwing speed:
image

But in the rate calculation, both the base and final rates are for after the Barrage Support modifier to throwing time is applied. Or another way to think of it, it technically calculates your throwing time for both using Barrage Support and not using it, but only shows the detailed calculation for if you are using it when you're using it.
image

This shows information about how much the Barrage Support is affecting your throw time(and what your throw time could be if you didn't use Barrage Supoprt), but also shows useful calculations about how much your modifiers to throwing speed are affecting your throw rate. When I was applying modifiers directly to the base time like most modifiers work, I couldn't figure out a way to make it show the numbers exactly like this. I only got it to work like this after I started storing the modifier as a separate variable then applying it with a separate calculation.

Anyway, that was a longwinded explanation, but that's my reasoning for doing it this way! Maybe something like "SkillTrapThrowingTime" and "SkillAttackTime" would be better? The wording on Barrage Support is specifically "Skills have 5% more ____ time" so I think these variable names would be a bit better.

**Comment by ppoelzl** [comment]
I'd say change the mod names to your suggestion and this PR is ready to be merged. Good work!

**Comment by Quotae** [comment]
Alright, changed! Should be good to go.

**Comment by Quotae** [comment]
Woops, found one more fix I needed to do. I noticed that Barrage Support could technically support any projectile attack skill as long as it wasn't triggered, channeled, or a minion. That means it could support melee weapon-based projectile skills like Molten Strike and give it a big DPS multiplier that it doesn't deserve. 

This isn't strictly my fault, though, it's just a combination of how support gems work and the way I coded it. Supports apparently can't tell what weapon type you're using, since someone tried adding a weaponTypes list to Barrage Support and it wasn't preventing anything.

I just set it so that the SequentialProjectiles flag only gets set if you're using a bow or a wand. It'll still incorrectly apply all the other modifiers to melee skills, but at least it won't give a huge DPS multiplier.

(Also, I can't just make it so that Melee skills can't use the support because of Frenzy and Elemental Hit, which have the Melee SkillType.)

**Comment by NickRyder** [comment]
This is not a satisfactory solution. We should continue to look into this until we can completely prevent the support gem from working on unintended gems.

**Comment by NickRyder** [comment]
Okay on further inspection it appears that the support grants the following stat:
```
        {
          "id": "skill_can_only_use_non_melee_weapons",
          "value": 1
        }
```

Looks like we need to add this stat into pob and then prevent melee weapons from using the skill if this stat is present.

**Comment by Quotae** [comment]
Maybe that would be better, but I realized another thing while I was trying to figure that out. There were a couple of skills like Rain of Arrows were also receiving the full DPS multiplier even though in-game it just adds 3 projectiles and makes the skill fire incredibly slowly.

I fixed this by adding two new SkillTypes, SkillCanBarrage and SkillCanSequentialProj, which should be self explanatory for what they do. I used SkillTypes because that's how Mirage Archer figures out what skills it can support.

Also, I was struggling quite a bit to figure out how to make the support look at what kind of weapon you're using when deciding if it can support a skill. It seems like all the other support gems that should look at what weapon type you're using either don't acknowledge it at all (Close Combat) or have workarounds so they don't have to acknowledge it (Mirage Archer). I looked into how PoB determines support gem compatibility and it's pretty limited. All it seems to check for are whether the gem can only support active skills, whether it can be supported at all, whether it's a minion skill(then goes to a separate check for minion compatibility), and SkillTypes. All that stuff seems to be in Modules/CalcTools.lua starting on line 75 if someone else would like to check into it more, but I decided to move onto SkillTypes since I knew that worked and would let me more easily differentiate between skills that can be supported by Barrage Support and which should get the DPS multiplier.

**Comment by Quotae** [comment]
Two more commits. I was talking to LocalIdentity on Discord and he told me that the SkillTypes stuff would need to manually redone every league, so he removed that stuff and did a couple of other things to make it all have the same functionality as the SkillTypes. I made those same changes to my branch and committed them here. One commit was to get it all finalized, the other was to add it all to the export scripts so it's automatically there when skills get re-exported next league.

I also made it so that Fury Valve stops the DPS multiplier from applying, since that item limits you to firing just one projectile. I noticed that error myself when I was planning a Fury Valve build. Luckily Fury Valve already used its own flag so I just made the DPS multiplier check for that flag before applying.

**Pull request merged**
