### PR TITLE
Fix cruelty calculation and default behavior

### PR DESCRIPTION
**Pull request by jfarrell731**
- Give cruelty support the buff it should. Cap the buff stacks at 40 to match with ingame.
- Make default behavior max stacks and change config option to override.
- Get cruelty effect on self from gem plus quality and apply to cruelty buff.

### CODE REVIEW

**Comment by summ1else** [comment]
Providing supporting documentation

Change is required due to 3.15.0 update to Cruelty Support
image

**Comment by jfarrell731** [comment]
After testing this morning, seems Cruelty flag as a buff is making the buffed skill show up under "Aura and Buff Skills" going to fix that.

**Comment by jfarrell731** [comment]
fixed flag for cruelty to be local, and check for the flag specifically in Calcperform and Calcs.

**Comment by jfarrell731** [comment]
Updated PR to move mod changes to sup_str.txt, properly generates mods now to track and apply cruelty buff

**Comment by jfarrell731** [comment]
With new mastery, need to update the parser to grab the increase effect and add it to the calculation

**Comment by jfarrell731** [comment]
Okay... I went to update the branch quick for the lua bits and it just broke... gonna reopen

**Pull request closed without merging**
